data = [
    {
        "id": "90113131698",
        "name": "Negocios",
        "color": "#03A2FD",
        "private": False,
        "avatar": None,
        "admin_can_manage": True,
        "statuses": [
            {
                "id": "p90113131698_DCnaeiSB",
                "status": "to do",
                "type": "open",
                "orderindex": 0,
                "color": "#87909e",
            },
            {
                "id": "p90113131698_g9uxhsQM",
                "status": "in progress",
                "type": "custom",
                "orderindex": 1,
                "color": "#1090e0",
            },
            {
                "id": "p90113131698_syqLtYOY",
                "status": "complete",
                "type": "closed",
                "orderindex": 2,
                "color": "#008844",
            },
        ],
        "multiple_assignees": True,
        "features": {
            "due_dates": {
                "enabled": True,
                "start_date": True,
                "remap_due_dates": True,
                "remap_closed_due_date": False,
            },
            "sprints": {"enabled": False},
            "time_tracking": {
                "enabled": True,
                "harvest": False,
                "rollup": False,
                "default_to_billable": 2,
            },
            "points": {"enabled": False},
            "custom_items": {"enabled": False},
            "priorities": {
                "enabled": True,
                "priorities": [
                    {
                        "color": "#f50000",
                        "id": "1",
                        "orderindex": "1",
                        "priority": "urgent",
                    },
                    {
                        "color": "#f8ae00",
                        "id": "2",
                        "orderindex": "2",
                        "priority": "high",
                    },
                    {
                        "color": "#6fddff",
                        "id": "3",
                        "orderindex": "3",
                        "priority": "normal",
                    },
                    {
                        "color": "#d8d8d8",
                        "id": "4",
                        "orderindex": "4",
                        "priority": "low",
                    },
                ],
            },
            "tags": {"enabled": True},
            "time_estimates": {"enabled": True, "rollup": False, "per_assignee": False},
            "check_unresolved": {
                "enabled": True,
                "subtasks": None,
                "checklists": None,
                "comments": None,
            },
            "zoom": {"enabled": True},
            "milestones": {"enabled": False},
            "custom_fields": {"enabled": True},
            "remap_dependencies": {"enabled": True},
            "dependency_warning": {"enabled": True},
            "status_pies": {"enabled": False},
            "multiple_assignees": {"enabled": True},
            "scheduler_enabled": False,
        },
        "archived": False,
    },
    {
        "id": "90113178861",
        "name": "Finanzas/Conta.",
        "color": "#e93d82",
        "private": False,
        "avatar": None,
        "admin_can_manage": False,
        "statuses": [
            {
                "id": "p90113178861_WUZJiB01",
                "status": "to do",
                "type": "open",
                "orderindex": 0,
                "color": "#87909e",
            },
            {
                "id": "p90113178861_zMN5ozq5",
                "status": "in progress",
                "type": "custom",
                "orderindex": 1,
                "color": "#5f55ee",
            },
            {
                "id": "p90113178861_PzDApYkK",
                "status": "complete",
                "type": "closed",
                "orderindex": 2,
                "color": "#008844",
            },
        ],
        "multiple_assignees": True,
        "features": {
            "due_dates": {
                "enabled": True,
                "start_date": True,
                "remap_due_dates": True,
                "remap_closed_due_date": False,
            },
            "sprints": {"enabled": False},
            "time_tracking": {
                "enabled": True,
                "harvest": False,
                "rollup": True,
                "default_to_billable": 2,
            },
            "points": {"enabled": False},
            "custom_items": {"enabled": False},
            "priorities": {
                "enabled": True,
                "priorities": [
                    {
                        "color": "#f50000",
                        "id": "1",
                        "orderindex": "1",
                        "priority": "urgent",
                    },
                    {
                        "color": "#f8ae00",
                        "id": "2",
                        "orderindex": "2",
                        "priority": "high",
                    },
                    {
                        "color": "#6fddff",
                        "id": "3",
                        "orderindex": "3",
                        "priority": "normal",
                    },
                    {
                        "color": "#d8d8d8",
                        "id": "4",
                        "orderindex": "4",
                        "priority": "low",
                    },
                ],
            },
            "tags": {"enabled": True},
            "time_estimates": {"enabled": True, "rollup": True, "per_assignee": False},
            "check_unresolved": {
                "enabled": True,
                "subtasks": None,
                "checklists": None,
                "comments": None,
            },
            "zoom": {"enabled": False},
            "milestones": {"enabled": True},
            "custom_fields": {"enabled": True},
            "remap_dependencies": {"enabled": True},
            "dependency_warning": {"enabled": True},
            "status_pies": {"enabled": True},
            "multiple_assignees": {"enabled": True},
            "scheduler_enabled": False,
        },
        "archived": False,
    },
    {
        "id": "90113178917",
        "name": "Omnichanel & IA",
        "color": "#3e63dd",
        "private": False,
        "avatar": None,
        "admin_can_manage": False,
        "statuses": [
            {
                "id": "p90113178917_db2TCRMT",
                "status": "to do",
                "type": "open",
                "orderindex": 0,
                "color": "#87909e",
            },
            {
                "id": "p90113178917_0tM9lMUW",
                "status": "in progress",
                "type": "custom",
                "orderindex": 1,
                "color": "#5f55ee",
            },
            {
                "id": "p90113178917_EaomYr6d",
                "status": "complete",
                "type": "closed",
                "orderindex": 2,
                "color": "#008844",
            },
        ],
        "multiple_assignees": True,
        "features": {
            "due_dates": {
                "enabled": True,
                "start_date": True,
                "remap_due_dates": True,
                "remap_closed_due_date": False,
            },
            "sprints": {"enabled": False},
            "time_tracking": {
                "enabled": True,
                "harvest": False,
                "rollup": True,
                "default_to_billable": 2,
            },
            "points": {"enabled": False},
            "custom_items": {"enabled": False},
            "priorities": {
                "enabled": True,
                "priorities": [
                    {
                        "color": "#f50000",
                        "id": "1",
                        "orderindex": "1",
                        "priority": "urgent",
                    },
                    {
                        "color": "#f8ae00",
                        "id": "2",
                        "orderindex": "2",
                        "priority": "high",
                    },
                    {
                        "color": "#6fddff",
                        "id": "3",
                        "orderindex": "3",
                        "priority": "normal",
                    },
                    {
                        "color": "#d8d8d8",
                        "id": "4",
                        "orderindex": "4",
                        "priority": "low",
                    },
                ],
            },
            "tags": {"enabled": True},
            "time_estimates": {"enabled": True, "rollup": True, "per_assignee": False},
            "check_unresolved": {
                "enabled": True,
                "subtasks": None,
                "checklists": None,
                "comments": None,
            },
            "zoom": {"enabled": False},
            "milestones": {"enabled": True},
            "custom_fields": {"enabled": True},
            "remap_dependencies": {"enabled": True},
            "dependency_warning": {"enabled": True},
            "status_pies": {"enabled": True},
            "multiple_assignees": {"enabled": True},
            "scheduler_enabled": False,
        },
        "archived": False,
    },
    {
        "id": "90113178944",
        "name": "Hardware & Redes",
        "color": "#12a594",
        "private": False,
        "avatar": None,
        "admin_can_manage": False,
        "statuses": [
            {
                "id": "p90113178944_yKF5sXA1",
                "status": "to do",
                "type": "open",
                "orderindex": 0,
                "color": "#87909e",
            },
            {
                "id": "p90113178944_hWTFj7NN",
                "status": "in progress",
                "type": "custom",
                "orderindex": 1,
                "color": "#5f55ee",
            },
            {
                "id": "p90113178944_hMW2x1Vv",
                "status": "complete",
                "type": "closed",
                "orderindex": 2,
                "color": "#008844",
            },
        ],
        "multiple_assignees": True,
        "features": {
            "due_dates": {
                "enabled": True,
                "start_date": True,
                "remap_due_dates": True,
                "remap_closed_due_date": False,
            },
            "sprints": {"enabled": False},
            "time_tracking": {
                "enabled": True,
                "harvest": False,
                "rollup": True,
                "default_to_billable": 2,
            },
            "points": {"enabled": False},
            "custom_items": {"enabled": False},
            "priorities": {
                "enabled": True,
                "priorities": [
                    {
                        "color": "#f50000",
                        "id": "1",
                        "orderindex": "1",
                        "priority": "urgent",
                    },
                    {
                        "color": "#f8ae00",
                        "id": "2",
                        "orderindex": "2",
                        "priority": "high",
                    },
                    {
                        "color": "#6fddff",
                        "id": "3",
                        "orderindex": "3",
                        "priority": "normal",
                    },
                    {
                        "color": "#d8d8d8",
                        "id": "4",
                        "orderindex": "4",
                        "priority": "low",
                    },
                ],
            },
            "tags": {"enabled": True},
            "time_estimates": {"enabled": True, "rollup": True, "per_assignee": False},
            "check_unresolved": {
                "enabled": True,
                "subtasks": None,
                "checklists": None,
                "comments": None,
            },
            "zoom": {"enabled": False},
            "milestones": {"enabled": True},
            "custom_fields": {"enabled": True},
            "remap_dependencies": {"enabled": True},
            "dependency_warning": {"enabled": True},
            "status_pies": {"enabled": True},
            "multiple_assignees": {"enabled": True},
            "emails": {"enabled": True},
            "scheduler_enabled": False,
        },
        "archived": False,
    },
    {
        "id": "90113178958",
        "name": "Software & Dev",
        "color": "#000",
        "private": False,
        "avatar": None,
        "admin_can_manage": False,
        "statuses": [
            {
                "id": "p90113178958_ao7hISum",
                "status": "to do",
                "type": "open",
                "orderindex": 0,
                "color": "#87909e",
            },
            {
                "id": "p90113178958_cCt4eumF",
                "status": "in progress",
                "type": "custom",
                "orderindex": 1,
                "color": "#5f55ee",
            },
            {
                "id": "p90113178958_PHrYRBp9",
                "status": "complete",
                "type": "closed",
                "orderindex": 2,
                "color": "#008844",
            },
        ],
        "multiple_assignees": True,
        "features": {
            "due_dates": {
                "enabled": True,
                "start_date": True,
                "remap_due_dates": True,
                "remap_closed_due_date": False,
            },
            "sprints": {"enabled": False},
            "time_tracking": {
                "enabled": True,
                "harvest": False,
                "rollup": True,
                "default_to_billable": 2,
            },
            "points": {"enabled": False},
            "custom_items": {"enabled": False},
            "priorities": {
                "enabled": True,
                "priorities": [
                    {
                        "color": "#f50000",
                        "id": "1",
                        "orderindex": "1",
                        "priority": "urgent",
                    },
                    {
                        "color": "#f8ae00",
                        "id": "2",
                        "orderindex": "2",
                        "priority": "high",
                    },
                    {
                        "color": "#6fddff",
                        "id": "3",
                        "orderindex": "3",
                        "priority": "normal",
                    },
                    {
                        "color": "#d8d8d8",
                        "id": "4",
                        "orderindex": "4",
                        "priority": "low",
                    },
                ],
            },
            "tags": {"enabled": True},
            "time_estimates": {"enabled": True, "rollup": True, "per_assignee": False},
            "check_unresolved": {
                "enabled": True,
                "subtasks": None,
                "checklists": None,
                "comments": None,
            },
            "zoom": {"enabled": False},
            "milestones": {"enabled": True},
            "custom_fields": {"enabled": True},
            "remap_dependencies": {"enabled": True},
            "dependency_warning": {"enabled": True},
            "status_pies": {"enabled": True},
            "multiple_assignees": {"enabled": True},
            "scheduler_enabled": False,
        },
        "archived": False,
    },
]
